version: "3.8"

services:
  frontend:
    build:
      context: ./my-webapp
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./my-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/calendar-app
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: [--auth]

volumes:
  mongo-data:
