version: "3.8"

services:
  frontend:
    build:
      context: ./my-webapp
      target: production
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    restart: always
    env_file:
      - .env.production

  backend:
    build: ./my-server
    ports:
      - "${BACKEND_PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/calendar-app
      - PORT=${PORT:-5000}
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: [--auth]

volumes:
  mongo-data:
