version: "3.8"

services:
  frontend:
    build:
      context: ./my-webapp
      target: development
    volumes:
      - ./my-webapp:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env.development
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT:-5001}/api

  backend:
    build: ./my-server
    volumes:
      - ./my-server:/app
      - /app/node_modules
    ports:
      - "${BACKEND_PORT:-5001}:${PORT:-5000}"
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/calendar-app
      - PORT=${PORT:-5000}
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
